spring.application.name=UserSecurity

spring.datasource.url=jdbc:postgresql://localhost:5433/UserDB
spring.datasource.username=postgres
spring.datasource.password=PostgreSQL123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB
server.tomcat.max-http-form-post-size=209715200
server.tomcat.max-swallow-size=-1
server.tomcat.max-part-count=50

spring.security.user.name=Admin
spring.security.user.password=Password